name: CI & Deploy to gh-pages subpaths

on:
  push:
    branches:
      - main
      - iteration1
      - iteration2
      - iteration3

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, iteration1, iteration2]
    if: github.ref == 'refs/heads/' + matrix.branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with: node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build for ${{ matrix.branch }}
        env:
          VITE_BASE: |
            ${{ matrix.branch == 'main' && '/' || '/' + matrix.branch + '/' }}
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: ${{ matrix.branch == 'main' && '' || matrix.branch }}
