name: CI & Deploy to gh-pages subpaths

on:
  push:
    branches:
      - main
      - iteration1
      - iteration2
      - iteration3

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            base: '/'
            dest: ''
          - branch: iteration1
            base: '/iteration1/'
            dest: iteration1
          - branch: iteration2
            base: '/iteration2/'
            dest: iteration2
          - branch: iteration3
            base: '/iteration3/'
            dest: iteration3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Build site for ${{ matrix.branch }}
        env:
          VITE_BASE: ${{ matrix.base }}
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: ${{ matrix.dest }}
