name: CI & Deploy to gh-pages

on:
  push:
    branches:
      - main
      - iteration1
      - iteration2
      - iteration3

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Determine deploy paths
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [ "$BRANCH" = "main" ]; then
            echo "BASE=/" >> $GITHUB_ENV
            echo "DEST=" >> $GITHUB_ENV
          else
            echo "BASE=/${BRANCH}/" >> $GITHUB_ENV
            echo "DEST=${BRANCH}" >> $GITHUB_ENV
          fi

      - name: Build site
        env:
          VITE_BASE: ${{ env.BASE }}
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: ${{ env.DEST }}
          force: true
